modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="thaumia"
version="0.7.5"
displayName="Thaumia!"
displayURL="https://curseforge.com/minecraft/mc-mods/thaumia"
logoFile="logo.png"
credits="LeoMP - Author"
authors="LeoMP"
description="A magic mod based on aura and taint. Originally intended to be an addon this mod became a independent mod"

[[dependencies.thaumia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.thaumia]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thaumia]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thaumia]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thaumia]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thaumia]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

